### PR TITLE
Remove redhat_csp_download module from project.

### PR DESCRIPTION
**Pull request by wtcross**
This change removes the redhat_csp_download module from the
project. It is provided by the jboss_eap role dependency.

### CODE REVIEW

**Comment by wtcross** [comment]
**This PR is dependent on [rhtconsulting/jboss_eap #30](https://github.com/rhtconsulting/jboss_eap/pull/30) being merged first.**

**Comment by kameshsampath** [comment]
@wtcross whats the plan behind this removal, are we planning to merge this as part of ansible or provide as as community module ?

**Comment by wtcross** [comment]
The module has now been added to the jboss_eap role, so it is no longer needed in this project. https://github.com/rhtconsulting/jboss_eap/pull/30

**Comment by sherl0cks** [comment]
#24 is the plan. @wtcross is it OK if I hold off until tomorrow to merge this? I'd like to double check with a clean checkout that things work alright.

**Comment by wtcross** [comment]
@sherl0cks, no problem! This is basically just a cleanup task.

**Comment by sherl0cks** [comment]
@wtcross ok that was my thought as well. greatly appreciate your contribution! thanks for getting involved

**Pull request merged**
