### PR TITLE
Moving Kamesh's Devops EAP Playbooks

### PR DESCRIPTION
**Pull request by kameshsampath**
Moving Kamesh's Devops EAP Playbooks to RH Consulting Ansible JBoss Middleware playbooks, first import

### CODE REVIEW

**Comment by sherl0cks** [comment]
@kameshsampath as discussed in email, let's use separate repos for roles and playbooks. Let's use this repo only for playbooks. EAP role stuff can go to https://github.com/rhtconsulting/ansible-eap-role

**Comment by kameshsampath** [comment]
Great will start to port roles to eap-role repo and keep playbooks to this repo.


Sent from Outlook Mobile






On Tue, Apr 5, 2016 at 10:28 AM -0700, "sherl0cks" <notifications@github.com> wrote:





@kameshsampath as discussed in email, let's use separate repos for roles and playbooks. Let's use this repo only for playbooks. EAP role stuff can go to https://github.com/rhtconsulting/ansible-eap-role

---

**Comment by alberttwong** [comment]
are we just waiting for the the updated pull (only playbooks) so we can merge?

**Comment by kameshsampath** [comment]
Albert,


Over next few days I will split the roles and playbooks into separate repo as discussed with @sherl0cks. And this repo will only have playbooks and eap-role repo will have all roles related to this.


Just wanted to split this into smaller commits as that will be easy for review and merge.




Sent from Outlook Mobile



From: Albert Wong

Sent: Thursday, 7 April, 1:07 AM

Subject: Re: [rhtconsulting/ansible-middleware-playbooks] Moving Kamesh's Devops EAP Playbooks (#1)

To: rhtconsulting/ansible-middleware-playbooks

Cc: Kamesh Sampath



are we just waiting for the the updated pull (only playbooks) so we can merge?

**Comment by sherl0cks** [comment]
Closing this request

**Pull request closed without merging**
